workflows:
  android-apk:
    name: Android APK Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
      - name: Flutter pub get
        script: |
          flutter pub get
      - name: Flutter build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - jose@techbyjr.com
        notify:
          success: true
          failure: true
